### ISSUE TITLE
Folder name not valid when installing on Windows

### ISSUE THREAD

**Issue by agenis** [20c/rdap#3]
While pip installing `rdap` according to instructions, I get the following error:

> Collecting rdap   Using cached
> https://files.pythonhosted.org/packages/76/8f/38ebde98eecf836c57727faccaef3b10be44ddfe9b2f5192b789e1792d89/rdap-0.5.0.tar.gz
> 
> Could not install packages due to an EnvironmentError: [WinError 267]
> Nom de rÚpertoire non valide:
> 'C:\\Users\\FLEURDA\\AppData\\Local\\Temp\\pip-install-n7gubvsj\\rdap\\Ctl/tmp/git@github.com:20c'

the error message translates: "folder name not valid". Here is the result of `IPython.sys_info()`:

    {'commit_hash': '8c47bbcb3',
     'commit_source': 'installation',
     'default_encoding': '1252',
     'ipython_path': 'C:\\Users\\FLEURDA\\Anaconda3\\envs\\python_35_for_rdap\\lib\\site-packages\\IPython',
     'ipython_version': '7.5.0',
     'os_name': 'nt',
     'platform': 'Windows-10-10.0.17134-SP0',
     'sys_executable': 'C:\\Users\\FLEURDA\\Anaconda3\\envs\\python_35_for_rdap\\python.exe',
     'sys_platform': 'win32',
     'sys_version': '3.5.6 |Anaconda, Inc.| (default, Aug 26 2018, 16:05:27) [MSC '
                    'v.1900 64 bit (AMD64)]'}

I don't understand what's going on with this error. I'm admin of my computer. I can successfully get any other package installed without error. According to [SO user response](https://stackoverflow.com/q/56024070/3871924), might be linked with a forbidden `:` character. Confirm the problem?

**Comment by grizz** [comment]
Thanks for the report, we'll have to find a windows box to test it on, can you confirm you did `pip install rdap`?

**Comment by agenis** [comment]
yes that's what I did, and I tried several variations with no-cache, admin, etc..

**Comment by grizz** [comment]
@agenis tested on windows, it's fixed in 0.5.2

**Comment by agenis** [comment]
indeed, working now on my computer. Thanks for the reactivity.
