### ISSUE TITLE
RIPE bootstrap url (default) does not respond to domain queries

### ISSUE THREAD

**Issue by lelutin** [20c/rdap#5]
With the default bootstrap URL, it's currently impossible to make domain queries. I've tried to get a bit more information about the situation but so far I couldn't see that domain-type searches are actually implemented by RIPE's service.

Queries work fine with `https://rdap.arin.net/bootstrap/` so it might be interesting to switch the default value to this.

Maybe you have more information about RIPE's RDAP service instance than I do, though.

**Comment by grizz** [comment]
Hrm, missed this ticket. Thanks, we will take a look!
